const MESSAGE = {
    CREATE_SUCCESS: 'CREATED SUCCESSFULLY',
    CREATE_FAILED: 'FAILED TO CREATE',
    RESOURCE_EXISTING: 'RESOURCE ALREADY EXISTING',
    RESOURCE_NOT_FOUND: 'RESOURCE NOT FOUND',
    UPDATE_SUCCESS: 'UPDATE SUCCESSFULLY',
    UPDATE_FAILED: 'UPDATE FAILED',
    DELETE_FAILED: 'DELETE FAILED',
    NOT_SUPPORTED: 'NOT SUPPORTED',
    INVALID_DATA_TYPE: 'INVALID DATA TYPE',
    INVALID_JSON_DATA: 'INVALID JSON DATA',
    INVALID_JSON_FORMAT: 'INVALID JSON FORMAT',
    UNKNOWN_ERROR: 'UNKNOWN ERROR'
}

module.exports = {
    MESSAGE
}