const MESSAGE = {
    CREATE_SUCCESS: 'CREATED SUCCESSFULLY',
    CREATE_FAILED: 'FAILED TO CREATE',
    RESOURCE_EXISTING: 'RESOURCE ALREADY EXISTING',
    RESOURCE_NOT_FOUND: 'RESOURCE NOT FOUND',
    UPDATE_SUCCESS: 'UPDATE SUCCESSFULLY',
    UPDATE_FAILED: 'UPDATE FAILED',
    DELETE_FAILED: 'DELETE FAILED',
    NOT_SUPPORTED: 'NOT SUPPORTED',
    INVALID_DATA: 'INVALID_DATA',
}

module.exports = {
    MESSAGE
}